spg_dict_html = {
            'P1': 'P1',
            'P-1': 'P<SPAN STYLE="text-decoration:overline;">1</SPAN>',
            'P2': 'P2',
            'P21': 'P21',
            'C2': 'C2',
            'Pm': 'Pm',
            'Pc': 'Pc',
            'Cm': 'Cm',
            'Cc': 'Cc',
            'P2/m': 'P2/m',
            'P21/m': 'P2<sub>1</sub>/m',
            'C2/m': 'C2/m',
            'P2/c': 'P2/c',
            'P21/c': 'P2<sub>1</sub>/c',
            'C2/c': 'C2/c',
            'P222': 'P222',
            'P2221': 'P222<sub>1</sub>',
            'P21212': 'P2<sub>1</sub>2<sub>1</sub>2',
            'P212121': 'P2<sub>1</sub>2<sub>1</sub>2<sub>1</sub>',
            'C2221': 'C222<sub>1</sub>',
            'C222': 'C222',
            'F222': 'F222',
            'I222': 'I222',
            'I212121': 'I2<sub>1</sub>2<sub>1</sub>2<sub>1</sub>',
            'Pmm2': 'Pmm2',
            'Pmc21': 'Pmc2<sub>1</sub>',
            'Pcc2': 'Pcc2',
            'Pma2': 'Pma2',
            'Pca21': 'Pca2<sub>1</sub>',
            'Pnc2': 'Pnc2',
            'Pmn21': 'Pmn2<sub>1</sub>',
            'Pba2': 'Pba2',
            'Pna21': 'Pna2<sub>1</sub>',
            'Pnn2': 'Pnn2',
            'Cmm2': 'Cmm2',
            'Cmc21': 'Cmc2<sub>1</sub>',
            'Ccc2': 'Ccc2',
            'Amm2': 'Amm2',
            'Abm2': 'Abm2',
            'Ama2': 'Ama2',
            'Aba2': 'Aba2',
            'Fmm2': 'Fmm2',
            'Fdd2': 'Fdd2',
            'Imm2': 'Imm2',
            'Iba2': 'Iba2',
            'Ima2': 'Ima2',
            'Pmmm': 'Pmmm',
            'Pnnn': 'Pnnn',
            'Pccm': 'Pccm',
            'Pban': 'Pban',
            'Pmma': 'Pmma',
            'Pnna': 'Pnna',
            'Pmna': 'Pmna',
            'Pcca': 'Pcca',
            'Pbam': 'Pbam',
            'Pccn': 'Pccn',
            'Pbcm': 'Pbcm',
            'Pnnm': 'Pnnm',
            'Pmmn': 'Pmmn',
            'Pbcn': 'Pbcn',
            'Pbca': 'Pbca',
            'Pnma': 'Pnma',
            'Cmcm': 'Cmcm',
            'Cmca': 'Cmca',
            'Cmce': 'Cmce',
            'Cmmm': 'Cmmm',
            'Cccm': 'Cccm',
            'Cmma': 'Cmma',
            'Cmme': 'Cmme',
            'Ccca': 'Ccca',
            'Ccce': 'Ccce',
            'Fmmm': 'Fmmm',
            'Fddd': 'Fddd',
            'Immm': 'Immm',
            'Ibam': 'Ibam',
            'Ibca': 'Ibca',
            'Imma': 'Imma',
            'P4': 'P4',
            'P41': 'P4<sub>1</sub>',
            'P42': 'P4<sub>2</sub>',
            'P43': 'P4<sub>3</sub>',
            'I4': 'I4',
            'I41': 'I4<sub>1</sub>',
            'P-4': 'P<SPAN STYLE="text-decoration:overline;">4</SPAN>',
            'I-4': 'I<SPAN STYLE="text-decoration:overline;">4</SPAN>',
            'P4m': 'P4/m',
            'P42/m': 'P4<sub>2</sub>/m',
            'P4n': 'P4/n',
            'P42n': 'P4<sub>2</sub>/n',
            'I4/m': 'I4/m',
            'I41a': 'I4<sub>1</sub>/a',
            'P422': 'P422',
            'P4212': 'P42<sub>1</sub>2',
            'P4122': 'P4<sub>1</sub>22',
            'P41212': 'P4<sub>1</sub>2<sub>1</sub>2',
            'P4222': 'P4<sub>2</sub>22',
            'P42212': 'P4<sub>2</sub>2<sub>1</sub>2',
            'P4322': 'P4<sub>3</sub>22',
            'P43212': 'P4<sub>3</sub>2<sub>1</sub>2',
            'I422': 'I422',
            'I4122': 'I4<sub>1</sub>22',
            'P4mm': 'P4mm',
            'P4bm': 'P4bm',
            'P42cm': 'P42cm',
            'P42nm': 'P42nm',
            'P4cc': 'P4cc',
            'P4nc': 'P4nc',
            'P42mc': 'P4<sub>2</sub>mc',
            'P42bc': 'P4<sub>2</sub>bc',
            'I4mm': 'I4mm',
            'I4cm': 'I4cm',
            'I41md': 'I4<sub>1</sub>md',
            'I41cd': 'I4<sub>1</sub>cd',
            'P-42m': 'P<SPAN STYLE="text-decoration:overline;">4</SPAN>2m',
            'P-42c': 'P<SPAN STYLE="text-decoration:overline;">4</SPAN>2c',
            'P-421m': 'P<SPAN STYLE="text-decoration:overline;">4</SPAN>2<sub>1</sub>m',
            'P-421c': 'P<SPAN STYLE="text-decoration:overline;">4</SPAN>2<sub>1</sub>c',
            'P-4m2': 'P<SPAN STYLE="text-decoration:overline;">4</SPAN>m2',
            'P-4c2': 'P<SPAN STYLE="text-decoration:overline;">4</SPAN>c2',
            'P-4b2': 'P<SPAN STYLE="text-decoration:overline;">4</SPAN>b2',
            'P-4n2': 'P<SPAN STYLE="text-decoration:overline;">4</SPAN>n2',
            'I-4m2': 'I<SPAN STYLE="text-decoration:overline;">4</SPAN>m2',
            'I-4c2': 'I<SPAN STYLE="text-decoration:overline;">4</SPAN>c2',
            'I-42m': 'I<SPAN STYLE="text-decoration:overline;">4</SPAN>2m',
            'I-42d': 'I<SPAN STYLE="text-decoration:overline;">4</SPAN>2d',
            'P4/mmm': 'P4/mmm',
            'P4/mcc': 'P4/mcc',
            'P4/nbm': 'P4/nbm',
            'P4/nnc': 'P4/nnc',
            'P4/mbm': 'P4/mbm',
            'P4/mnc': 'P4/mnc',
            'P4/nmm': 'P4/nmm',
            'P4/ncc': 'P4/ncc',
            'P42/mmc': 'P4<sub>2</sub>/mmc',
            'P42/mcm': 'P4<sub>2</sub>/mcm',
            'P42/nbc': 'P4<sub>2</sub>/nbc',
            'P42/nnm': 'P4<sub>2</sub>/nnm',
            'P42/mbc': 'P4<sub>2</sub>/mbc',
            'P42/mnm': 'P4<sub>2</sub>/mnm',
            'P42/nmc': 'P4<sub>2</sub>/nmc',
            'P42/ncm': 'P4<sub>2</sub>/ncm',
            'I4/mmm': 'I4/mmm',
            'I4/mcm': 'I4/mcm',
            'I41/amd': 'I4<sub>1</sub>/amd',
            'I41/acd': 'I4<sub>1</sub>/acd',
            'P3': 'P3',
            'P31': 'P3<sub>1</sub>',
            'P32': 'P3<sub>2</sub>',
            'R3': 'R3',
            'P-3': 'P<SPAN STYLE="text-decoration:overline;">3</SPAN>',
            'R-3': 'R<SPAN STYLE="text-decoration:overline;">3</SPAN>',
            'P312': 'P312',
            'P321': 'P321',
            'P3112': 'P3<sub>1</sub>12',
            'P3121': 'P3<sub>1</sub>21',
            'P3212': 'P3<sub>2</sub>12',
            'P3221': 'P3<sub>2</sub>21',
            'R32': 'R32',
            'P3m1': 'P3m1',
            'P31m': 'P31m',
            'P3c1': 'P3c1',
            'P31c': 'P31c',
            'R3m': 'R3m',
            'R3c': 'R3c',
            'P-31m': 'P<SPAN STYLE="text-decoration:overline;">3</SPAN>1m',
            'P-31c': 'P<SPAN STYLE="text-decoration:overline;">3</SPAN>1c',
            'P-3m1': 'P<SPAN STYLE="text-decoration:overline;">3</SPAN>m1',
            'P-3c1': 'P<SPAN STYLE="text-decoration:overline;">3</SPAN>c1',
            'R-3m': 'R<SPAN STYLE="text-decoration:overline;">3</SPAN>m',
            'R-3c': 'R<SPAN STYLE="text-decoration:overline;">3</SPAN>c',
            'P6': 'P6',
            'P61': 'P6<sub>1</sub>',
            'P65': 'P6<sub>5</sub>',
            'P62': 'P6<sub>2</sub>',
            'P64': 'P6<sub>4</sub>',
            'P63': 'P6<sub>3</sub>',
            'P-6': 'P<SPAN STYLE="text-decoration:overline;">6</SPAN>',
            'P6m': 'P6/m',
            'P63/m': 'P6<sub>3</sub>/m',
            'P622': 'P622',
            'P6122': 'P6<sub>1</sub>22',
            'P6522': 'P6<sub>5</sub>22',
            'P6222': 'P6<sub>2</sub>22',
            'P6422': 'P6<sub>4</sub>22',
            'P6322': 'P6<sub>3</sub>22',
            'P6mm': 'P6mm',
            'P6cc': 'P6cc',
            'P63cm': 'P6<sub>3</sub>cm',
            'P63mc': 'P6<sub>3</sub>mc',
            'P-6m2': 'P<SPAN STYLE="text-decoration:overline;">6</SPAN>m2',
            'P-6c2': 'P<SPAN STYLE="text-decoration:overline;">6</SPAN>c2',
            'P-62m': 'P<SPAN STYLE="text-decoration:overline;">6</SPAN>2m',
            'P-62c': 'P<SPAN STYLE="text-decoration:overline;">6</SPAN>2c',
            'P6mmm': 'P6/mmm',
            'P6mcc': 'P6/mcc',
            'P63/mcm': 'P6<sub>3</sub>/mcm',
            'P63/mmc': 'P6<sub>3</sub>/mmc',
            'P23': 'P23',
            'F23': 'F23',
            'I23': 'I23',
            'P213': 'P2<sub>1</sub>3',
            'I213': 'I2<sub>1</sub>3',
            'Pm-3': 'Pm<SPAN STYLE="text-decoration:overline;">3</SPAN>',
            'Pn-3': 'Pn<SPAN STYLE="text-decoration:overline;">3</SPAN>',
            'Fm-3': 'Fm<SPAN STYLE="text-decoration:overline;">3</SPAN>',
            'Fd-3': 'Fd<SPAN STYLE="text-decoration:overline;">3</SPAN>',
            'Im-3': 'Im<SPAN STYLE="text-decoration:overline;">3</SPAN>',
            'Pa-3': 'Pa<SPAN STYLE="text-decoration:overline;">3</SPAN>',
            'Ia-3': 'Ia<SPAN STYLE="text-decoration:overline;">3</SPAN>',
            'P432': 'P432',
            'P4232': 'P4<sub>2</sub>32',
            'F432': 'F432',
            'F4132': 'F4<sub>1</sub>32',
            'I432': 'I432',
            'P4332': 'P4<sub>3</sub>32',
            'P4132': 'P4<sub>1</sub>32',
            'I4132': 'I4<sub>1</sub>32',
            'P-43m': 'P<SPAN STYLE="text-decoration:overline;">4</SPAN>3m',
            'F-43m': 'F<SPAN STYLE="text-decoration:overline;">4</SPAN>3m',
            'I-43m': 'I<SPAN STYLE="text-decoration:overline;">4</SPAN>3m',
            'P-43n': 'P<SPAN STYLE="text-decoration:overline;">4</SPAN>3n',
            'F-43c': 'F<SPAN STYLE="text-decoration:overline;">4</SPAN>3c',
            'I-43d': 'I<SPAN STYLE="text-decoration:overline;">4</SPAN>3d',
            'Pm-3m': 'Pm<SPAN STYLE="text-decoration:overline;">3</SPAN>m',
            'Pn-3n': 'Pn<SPAN STYLE="text-decoration:overline;">3</SPAN>n',
            'Pm-3n': 'Pm<SPAN STYLE="text-decoration:overline;">3</SPAN>n',
            'Pn-3m': 'Pn<SPAN STYLE="text-decoration:overline;">3</SPAN>m',
            'Fm-3m': 'Fm<SPAN STYLE="text-decoration:overline;">3</SPAN>m',
            'Fm-3c': 'Fm<SPAN STYLE="text-decoration:overline;">3</SPAN>c',
            'Fd-3m': 'Fd<SPAN STYLE="text-decoration:overline;">3</SPAN>m',
            'Fd-3c': 'Fd<SPAN STYLE="text-decoration:overline;">3</SPAN>c',
            'Im-3m': 'Im<SPAN STYLE="text-decoration:overline;">3</SPAN>m',
            'Ia-3d': 'Ia<SPAN STYLE="text-decoration:overline;">3</SPAN>d',
}
spg_dict_tex = {
            'P1': r'$P1$',
            'P-1': r'$P\overline{1}$',
            'P2': r'$P2$',
            'P21': r'$P21$',
            'C2': r'$C2$',
            'Pm': r'$Pm$',
            'Pc': r'$Pc$',
            'Cm': r'$Cm$',
            'Cc': r'$Cc$',
            'P2m': r'$P2/m$',
            'P21m': r'$P2_1/m$',
            'C2m': r'$C2/m$',
            'P2c': r'$P2/c$',
            'P21c': r'$P2_1/c$',
            'C2c': r'$C2/c$',
            'P222': r'$P222$',
            'P2221': r'$P222_1$',
            'P21212': r'$P2_12_12$',
            'P212121': r'$P2_12_12_1$',
            'C2221': r'$C222_1$',
            'C222': r'$C222$',
            'F222': r'$F222$',
            'I222': r'$I222$',
            'I212121': r'$I2_12_12_1$',
            'Pmm2': r'$Pmm2$',
            'Pmc21': r'$Pmc2_1$',
            'Pcc2': r'$Pcc2$',
            'Pma2': r'$Pma2$',
            'Pca21': r'$Pca2_1$',
            'Pnc2': r'$Pnc2$',
            'Pmn21': r'$Pmn2_1$',
            'Pba2': r'$Pba2$',
            'Pna21': r'$Pna2_1$',
            'Pnn2': r'$Pnn2$',
            'Cmm2': r'$Cmm2$',
            'Cmc21': r'$Cmc2_1$',
            'Ccc2': r'$Ccc2$',
            'Amm2': r'$Amm2$',
            'Abm2': r'$Abm2$',
            'Ama2': r'$Ama2$',
            'Aba2': r'$Aba2$',
            'Fmm2': r'$Fmm2$',
            'Fdd2': r'$Fdd2$',
            'Imm2': r'$Imm2$',
            'Iba2': r'$Iba2$',
            'Ima2': r'$Ima2$',
            'Pmmm': r'$Pmmm$',
            'Pnnn': r'$Pnnn$',
            'Pccm': r'$Pccm$',
            'Pban': r'$Pban$',
            'Pmma': r'$Pmma$',
            'Pnna': r'$Pnna$',
            'Pmna': r'$Pmna$',
            'Pcca': r'$Pcca$',
            'Pbam': r'$Pbam$',
            'Pccn': r'$Pccn$',
            'Pbcm': r'$Pbcm$',
            'Pnnm': r'$Pnnm$',
            'Pmmn': r'$Pmmn$',
            'Pbcn': r'$Pbcn$',
            'Pbca': r'$Pbca$',
            'Pnma': r'$Pnma$',
            'Cmcm': r'$Cmcm$',
            'Cmca': r'$Cmca$',
            'Cmce': r'$Cmce$',
            'Cmmm': r'$Cmmm$',
            'Cccm': r'$Cccm$',
            'Cmma': r'$Cmma$',
            'Cmme': r'$Cmme$',
            'Ccca': r'$Ccca$',
            'Ccce': r'$Ccce$',
            'Fmmm': r'$Fmmm$',
            'Fddd': r'$Fddd$',
            'Immm': r'$Immm$',
            'Ibam': r'$Ibam$',
            'Ibca': r'$Ibca$',
            'Imma': r'$Imma$',
            'P4': r'$P4$',
            'P41': r'$P4_1$',
            'P42': r'$P4_2$',
            'P43': r'$P4_3$',
            'I4': r'$I4$',
            'I41': r'$I4_1$',
            'P-4': r'$P\overline{4}$',
            'I-4': r'$I\overline{4}$',
            'P4m': r'$P4/m$',
            'P42m': r'$P4_2/m$',
            'P4n': r'$P4/n$',
            'P42n': r'$P4_2/n$',
            'I4m': r'$I4/m$',
            'I41a': r'$I4_1/a$',
            'P422': r'$P422$',
            'P4212': r'$P42_12$',
            'P4122': r'$P4_122$',
            'P41212': r'$P4_12_12$',
            'P4222': r'$P4_222$',
            'P42212': r'$P4_22_12$',
            'P4322': r'$P4_322$',
            'P43212': r'$P4_32_12$',
            'I422': r'$I422$',
            'I4122': r'$I4_122$',
            'P4mm': r'$P4mm$',
            'P4bm': r'$P4bm$',
            'P42cm': r'$P42cm$',
            'P42nm': r'$P42nm$',
            'P4cc': r'$P4cc$',
            'P4nc': r'$P4nc$',
            'P42mc': r'$P4_2mc$',
            'P42bc': r'$P4_2bc$',
            'I4mm': r'$I4mm$',
            'I4cm': r'$I4cm$',
            'I41md': r'$I4_1md$',
            'I41cd': r'$I4_1cd$',
            'P-42m': r'$P\overline{4}2m$',
            'P-42c': r'$P\overline{4}2c$',
            'P-421m': r'$P\overline{4}2_1m$',
            'P-421c': r'$P\overline{4}2_1c$',
            'P-4m2': r'$P\overline{4}m2$',
            'P-4c2': r'$P\overline{4}c2$',
            'P-4b2': r'$P\overline{4}b2$',
            'P-4n2': r'$P\overline{4}n2$',
            'I-4m2': r'$I\overline{4}m2$',
            'I-4c2': r'$I\overline{4}c2$',
            'I-42m': r'$I\overline{4}2m$',
            'I-42d': r'$I\overline{4}2d$',
            'P4mmm': r'$P4/mmm$',
            'P4mcc': r'$P4/mcc$',
            'P4nbm': r'$P4/nbm$',
            'P4nnc': r'$P4/nnc$',
            'P4mbm': r'$P4/mbm$',
            'P4mnc': r'$P4/mnc$',
            'P4nmm': r'$P4/nmm$',
            'P4ncc': r'$P4/ncc$',
            'P42mmc': r'$P4_2/mmc$',
            'P42mcm': r'$P4_2/mcm$',
            'P42nbc': r'$P4_2/nbc$',
            'P42nnm': r'$P4_2/nnm$',
            'P42mbc': r'$P4_2/mbc$',
            'P42mnm': r'$P4_2/mnm$',
            'P42nmc': r'$P4_2/nmc$',
            'P42ncm': r'$P4_2/ncm$',
            'I4mmm': r'$I4/mmm$',
            'I4mcm': r'$I4/mcm$',
            'I41amd': r'$I4_1/amd$',
            'I41acd': r'$I4_1/acd$',
            'P3': r'$P3$',
            'P31': r'$P3_1$',
            'P32': r'$P3_2$',
            'R3': r'$R3$',
            'P-3': r'$P\overline{3}$',
            'R-3': r'$R\overline{3}$',
            'P312': r'$P312$',
            'P321': r'$P321$',
            'P3112': r'$P3_112$',
            'P3121': r'$P3_121$',
            'P3212': r'$P3_212$',
            'P3221': r'$P3_221$',
            'R32': r'$R32$',
            'P3m1': r'$P3m1$',
            'P31m': r'$P31m$',
            'P3c1': r'$P3c1$',
            'P31c': r'$P31c$',
            'R3m': r'$R3m$',
            'R3c': r'$R3c$',
            'P-31m': r'$P\overline{3}1m$',
            'P-31c': r'$P\overline{3}1c$',
            'P-3m1': r'$P\overline{3}m1$',
            'P-3c1': r'$P\overline{3}c1$',
            'R-3m': r'$R\overline{3}m$',
            'R-3c': r'$R\overline{3}c$',
            'P6': r'$P6$',
            'P61': r'$P6_1$',
            'P65': r'$P6_5$',
            'P62': r'$P6_2$',
            'P64': r'$P6_4$',
            'P63': r'$P6_3$',
            'P-6': r'$P\overline{6}$',
            'P6m': r'$P6/m$',
            'P63m': r'$P6_3/m$',
            'P622': r'$P622$',
            'P6122': r'$P6_122$',
            'P6522': r'$P6_522$',
            'P6222': r'$P6_222$',
            'P6422': r'$P6_422$',
            'P6322': r'$P6_322$',
            'P6mm': r'$P6mm$',
            'P6cc': r'$P6cc$',
            'P63cm': r'$P6_3cm$',
            'P63mc': r'$P6_3mc$',
            'P-6m2': r'$P\overline{6}m2$',
            'P-6c2': r'$P\overline{6}c2$',
            'P-62m': r'$P\overline{6}2m$',
            'P-62c': r'$P\overline{6}2c$',
            'P6mmm': r'$P6/mmm$',
            'P6mcc': r'$P6/mcc$',
            'P63mcm': r'$P6_3/mcm$',
            'P63mmc': r'$P6_3/mmc$',
            'P23': r'$P23$',
            'F23': r'$F23$',
            'I23': r'$I23$',
            'P213': r'$P2_13$',
            'I213': r'$I2_13$',
            'Pm-3': r'$Pm\overline{3}$',
            'Pn-3': r'$Pn\overline{3}$',
            'Fm-3': r'$Fm\overline{3}$',
            'Fd-3': r'$Fd\overline{3}$',
            'Im-3': r'$Im\overline{3}$',
            'Pa-3': r'$Pa\overline{3}$',
            'Ia-3': r'$Ia\overline{3}$',
            'P432': r'$P432$',
            'P4232': r'$P4_232$',
            'F432': r'$F432$',
            'F4132': r'$F4_132$',
            'I432': r'$I432$',
            'P4332': r'$P4_332$',
            'P4132': r'$P4_132$',
            'I4132': r'$I4_132$',
            'P-43m': r'$P\overline{4}3m$',
            'F-43m': r'$F\overline{4}3m$',
            'I-43m': r'$I\overline{4}3m$',
            'P-43n': r'$P\overline{4}3n$',
            'F-43c': r'$F\overline{4}3c$',
            'I-43d': r'$I\overline{4}3d$',
            'Pm-3m': r'$Pm\overline{3}m$',
            'Pn-3n': r'$Pn\overline{3}n$',
            'Pm-3n': r'$Pm\overline{3}n$',
            'Pn-3m': r'$Pn\overline{3}m$',
            'Fm-3m': r'$Fm\overline{3}m$',
            'Fm-3c': r'$Fm\overline{3}c$',
            'Fd-3m': r'$Fd\overline{3}m$',
            'Fd-3c': r'$Fd\overline{3}c$',
            'Im-3m': r'$Im\overline{3}m$',
            'Ia-3d': r'$Ia\overline{3}d$',
}
